name: AuthPlugin
main: es.networkersmc.auth.AuthPlugin
version: ${project.version}
load: POSTWORLD
depend: [DenderaBukkit]

author: Alberto Mimbrero
description: Authentication service for the Networkers Minecraft network.
website: https://github.com/NetworkersES/auth

# Legacy auth commands for people used to AuthMe
commands:
  register:
    aliases: ["r", "reg"]
  login:
    aliases: ["l"]